import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFireDatabase } from '@angular/fire/database';

@Injectable({
  providedIn: 'root'
})
export class FirebaseService 
{
  versions: Observable<any[]>;
  versionsLength : number;
  // versions = [];

  constructor(public db: AngularFireDatabase) 
  {
    this.versions = db.list('versions').valueChanges();
    this.versions.subscribe((res) => 
    {
      this.versionsLength = res.length;
    });
  }

  AddVersion(versionName)
  {
    const itemsRef = this.db.list('versions')
    itemsRef.set(String(this.versionsLength++),
    {
      isCurrent: false,
      name: versionName
    });
  }

  PublishVersion(versionKey) {
      const itemsRef = this.db.list('versions');
      itemsRef.set(String(versionKey) + "/isCurrent", true);
  }

  UnpublishVersion(versionKey) {
    const itemsRef = this.db.list('versions');
    itemsRef.set(String(versionKey) + "/isCurrent", false);
  }

  EditChange(versionKey, result, theData, changeParam)
  {
    let obj:any = {};
    this.db.database.ref('versions/' + String(versionKey))
      .on('value', snap => {
        obj = snap.val();
      })

    let changes = [];
    if(obj.changes === undefined) {
      obj = {
        ...obj,
        changes: changes
      }
    }

    let newChange = changeParam !== 'remove kebab' ?
        (changeParam !== 'add' ? {
            classes: changeParam === 'classes' ? result : theData.classes,
            inner: changeParam === 'inner' ? result : theData.inner,
            src: changeParam === 'src' ? result : (theData.src !== undefined ? theData.src : ""),
            styles: changeParam === 'styles' ? result : theData.styles,
            autoGeneratedID: theData.id
        } : {
            add: true,
            actionData: result,
            autoGeneratedID: theData.id
        }) : {
            remove: true,
            autoGeneratedID: theData.id
        };

    obj.changes.push(newChange);

    const itemsRef = this.db.list('versions/');

    itemsRef.set(String(versionKey), obj);
  }
              // {
              //   classes: "class1 class2 classn",
              //   inner: "innerText goes here",
              //   src: "",
              //   styles: 
              //   {
              //     style1: "stuff1",
              //     style2: "stuff2",
              //   },
              //   autoGeneratedID: "idhaccx"
              // },
}
