import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { AngularFireDatabase } from '@angular/fire/database';

@Injectable({
  providedIn: 'root'
})
export class FirebaseService 
{
  versions: Observable<any[]>;

  constructor(public db: AngularFireDatabase) 
  {
    this.versions = db.list('versions').valueChanges();
    this.versions.subscribe((res) => 
    {
      console.log(res);
    });
  }

  AddVersion(versionName)
  {
    const itemsRef = this.db.list('versions')
    itemsRef.push(
    {
      isCurrent: false,
      name: versionName
    });
  }
              // {
              //   classes: "class1 class2 classn",
              //   inner: "innerText goes here",
              //   src: "",
              //   styles: 
              //   {
              //     style1: "stuff1",
              //     style2: "stuff2",
              //   },
              //   autoGeneratedID: "idhaccx"
              // },
}
